### ISSUE TITLE
Next major version of Bluebird

### ISSUE THREAD

**Issue by davydkov** [L7labs/sinon-bluebird#10]
Recently a new major version of bluebird (3.0.5) was released.
But your library has strict requirement of `peerDependency`

Can you update your package.json and also release next major version?
Seems like there are no breaking changes

**Comment by toddbluhm** [comment]
Yeah I will do this right now.

**Comment by toddbluhm** [comment]
Just published this to npm as 3.0.0.

Let me know if you have any issues.
