### ISSUE TITLE
How to use with Karma?

### ISSUE THREAD

**Issue by andrefox333** [L7labs/sinon-bluebird#14]
Hi, ideas on how to use with Karma?

**Comment by toddbluhm** [comment]
What issues are you running into specifically? Not sure why this wouldn't work under karma. This lib integrates with `sinon` and `bluebird` and neither of them really have anything specific to do with a test framework, nor should they be test framework dependent. 

Maybe you are forgetting to include bluebird as the browser promise shim? Maybe Karma is shimming `Promise` to use the ES6 promise still which does not include a lot of bluebird special methods. While this lib does not specifically use `Promise` for that vary reason, perhaps you are passing in a non-bluebird promise?

I am happy to help however I can 😄

**Comment by toddbluhm** [comment]
Closing this due to no response. Feel free to reopen if you still have questions.
